# Permalinks
permalink:           pretty

# Setup
title:               LEaP!
tagline:             Journey of becoming Data Scienetist 
url:                 http://rochnysu.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              V. Su
  url:               https://twitter.com/
  email:             rochnysu@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/rochnysu

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
